/**
 * Write a translation template.
 *
 *     node tools/i18n_extract.mjs ar > src/data/strings.ar.js
 *
 * Collects every translatable string in the game -- dialogue, choice text,
 * press claims, cast names, exhibit copy -- against the same keys the player
 * looks them up by, and prints a module a translator can fill in.
 *
 * Dropping the finished file at src/data/strings.<code>.js is the entire
 * install step: `?lang=<code>` then plays in that language. Nothing else in the
 * codebase changes, and any key left untranslated falls back to English rather
 * than rendering blank.
 *
 * Re-running against an existing bundle keeps the translations already done and
 * marks anything new, so this is safe to run after the script changes.
 */

import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { SCENES, INTERVIEWS } from "../src/data/scenes.js";
import { CAST, EXHIBITS, CONTRADICTIONS, CASE, VERDICTS } from "../src/data/case.js";
import { keyed } from "../src/engine/script.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const code = process.argv[2];

if (!code || !/^[a-z]{2,3}(-[A-Za-z]+)?$/.test(code)) {
  console.error("Usage: node tools/i18n_extract.mjs <locale-code>    e.g. ar, fr, pt-BR");
  process.exit(1);
}

/** key -> English source. Insertion order is the order a translator reads. */
const entries = new Map();
const add = (key, english) => {
  if (typeof english === "string" && english.trim()) entries.set(key, english);
};

add("title.file", CASE.file);
add("title.name", CASE.title);
add("title.strap", CASE.strapline);

for (const [id, person] of Object.entries(CAST)) {
  add(`cast.${id}.name`, person.name);
  add(`cast.${id}.role`, person.role);
}

for (const [id, exhibit] of Object.entries(EXHIBITS)) {
  add(`exhibit.${id}.name`, exhibit.name);
  add(`exhibit.${id}.summary`, exhibit.summary);
  add(`exhibit.${id}.note`, exhibit.note);
}

for (const [id, contradiction] of Object.entries(CONTRADICTIONS)) {
  add(`proof.${id}.claim`, contradiction.claim);
  add(`proof.${id}.verdict`, contradiction.verdict);
}

for (const [id, v] of Object.entries(VERDICTS)) {
  add(`verdict.${id}.headline`, v.headline);
  add(`verdict.${id}.body`, v.body);
}

for (const interview of INTERVIEWS) add(`interview.${interview.person}.teaser`, interview.teaser);

for (const [id, scene] of Object.entries(SCENES)) {
  for (const { node, key } of keyed(scene.script, id)) {
    add(key, node.text);
    if (node.press) add(`${key}.claim`, node.press.claim);
    if (node.choice) {
      node.choice.forEach((option, index) => add(`${key}.choice.${index}`, option.text));
    }
  }
}

// Interface strings live in the code as t("key", "English"), not in the data.
function sourceFiles(directory) {
  const out = [];
  for (const entry of readdirSync(directory)) {
    const full = join(directory, entry);
    if (statSync(full).isDirectory()) out.push(...sourceFiles(full));
    else if (entry.endsWith(".js")) out.push(full);
  }
  return out;
}

for (const file of sourceFiles(join(ROOT, "src"))) {
  const source = readFileSync(file, "utf8");
  for (const [, key, english] of source.matchAll(/\btf?\(\s*"([^"]+)"\s*,\s*"((?:[^"\\]|\\.)*)"/g)) {
    // Dialogue keys are generated at runtime and already collected above.
    if (/^(intro|scene:|interview:)/.test(key)) continue;
    add(key, english.replace(/\\"/g, '"'));
  }
}

// Keep anything already translated.
const target = join(ROOT, "src", "data", `strings.${code}.js`);
const existing = new Map();
if (existsSync(target)) {
  const source = readFileSync(target, "utf8");
  for (const [, key, value] of source.matchAll(/^\s*"((?:[^"\\]|\\.)*)":\s*"((?:[^"\\]|\\.)*)",?\s*$/gm)) {
    existing.set(key, value);
  }
}

const quote = (text) => text.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

let done = 0;
const lines = [];
for (const [key, english] of entries) {
  const translated = existing.get(key);
  if (translated) {
    done += 1;
    lines.push(`  // ${english.replace(/\s+/g, " ").slice(0, 96)}`);
    lines.push(`  "${quote(key)}": "${translated}",`);
  } else {
    lines.push(`  // TODO  ${english.replace(/\s+/g, " ")}`);
    lines.push(`  "${quote(key)}": "",`);
  }
  lines.push("");
}

console.log(`/**
 * ${code} translation bundle.
 *
 * Generated by tools/i18n_extract.mjs. Each entry is preceded by its English
 * source. Fill in the empty strings; anything left empty falls back to English,
 * so a partial translation is safe to ship.
 *
 * Right-to-left languages need nothing extra -- the engine sets the document
 * direction from the locale code and the stylesheets are written in logical
 * properties.
 *
 * ${done} of ${entries.size} strings translated.
 */

export const STRINGS = {
${lines.join("\n")}};
`);
